version: "3"
services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./db-migration-scripts/create_table.sql:/docker-entrypoint-initdb.d/create_table.sql
  api:
    build: ./api
    depends_on:
      - db
    ports:
      - 3030:3030
    environment:
      DB_HOST: db
      DB_USER: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: 5432
  ui:
    build: ./ui
    depends_on:
      - api
    environment:
      API_URL: ${API_URL}
    ports:
      - 3000:3000
